version: '3.8'

services:
  # 애플리케이션 서비스
  deokhugam-app:
    container_name: deokhugam-app
    build: . # 현재 디렉토리의 Dockerfile 사용
    ports:
      - "8080:8080" # 호스트 8080, 컨테이너 8080
    env_file:
      - .env # 환경변수 주입
    environment:
      # DB 접속 정보
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
      # Storage 설정 (추가)
      - STORAGE_TYPE=${STORAGE_TYPE}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - REDIS_HOST=deokhugam-redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=deokhugam-kafka:29092
    depends_on:
      deokhugam-db:
        condition: service_healthy
      deokhugam-redis:
        condition: service_started
      deokhugam-kafka:
        condition: service_started
    volumes:
      - ./.deokhugam:/app/.deokhugam # 로컬 파일 저장소
      - ./.deokhugam-files:/app/.deokhugam-files # 파일 저장소
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - deokhugam-network

  # Zookeeper (카프카 메타데이터 관리)
  deokhugam-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: deokhugam-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # [추가] 주키퍼 데이터 영속성 설정
    volumes:
      - ./.zookeeper-data:/var/lib/zookeeper/data
      - ./.zookeeper-log:/var/lib/zookeeper/log
    networks:
      - deokhugam-network

  # Kafka Broker
  deokhugam-kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: deokhugam-kafka
    depends_on:
      - deokhugam-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: deokhugam-zookeeper:2181
      # INTERNAL로 통일한다.
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://deokhugam-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # [추가] 카프카 메시지 데이터 영속성 설정 (EBS 저장 공간 활용)
    volumes:
      - ./.kafka-data:/var/lib/kafka/data
    networks:
      - deokhugam-network

  # DB 서비스 (PostgreSQL)
  deokhugam-db:
    container_name: deokhugam-db
    image: postgres:17.2
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data # DB 데이터 유지
      # 초기화 스크립트 (최초 실행 시 자동 실행)
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432" # 호스트 접속 가능
    networks:
      - deokhugam-network

  # 프로메테우스
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - deokhugam-network
    restart: always

  # 그라파나
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - deokhugam-network
    restart: always

  # Redis
  deokhugam-redis:
    container_name: deokhugam-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - deokhugam-network
    restart: always

networks:
  deokhugam-network:
    driver: bridge