spring:
  application:
    name: SB08-Deokhugam-teamGwanwoong
  profiles:
    active: prod

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,prometheus
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}