input {
  jdbc {
    # 도커 내부 경로로 지정
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql.jar"
    # 사용할 드라이버의 실제 클래스 명칭
    jdbc_driver_class => "org.postgresql.Driver"
    # DB의 주소
    jdbc_connection_string => "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"
    jdbc_user => "${PGUSER}"
    jdbc_password => "${PGPASSWORD}"

    # 페이징 및 스케쥴 설정
    jdbc_paging_enabled => true
    # 데이터를 5000개씩 끊어서 가져옴(성능을 위해)
    jdbc_page_size => 100
    schedule => "* * * * *" #1분마다 동기화
    # 실제로 가져올 데이터
    # logstash는 마지막에 가져온 데이터의 updated_at 시간 파일을 기록함
    # 다음 실행때는 그 시간 이후로 수정된 데이터만 가져옴, 풀 스캔할 필요 없음
    statement => "
        SELECT r.id, r.content, r.rating, r.updated_at,
               TO_CHAR(r.created_at, 'YYYY-MM-DD')  'T'  TO_CHAR(r.created_at, 'HH24:MI:SS.MS') || 'Z' AS created_at,
               b.id AS book_id, b.title AS book_title,
               u.id AS user_id, u.nickname AS user_nickname
        FROM reviews r
        JOIN books b ON r.book_id = b.id
        JOIN users u ON r.user_id = u.id
        WHERE r.deleted_at IS NULL AND r.updated_at > :sql_last_value
        ORDER BY r.updated_at ASC
    "

    # 마지막으로 읽은 시점(:sql_last_value)을 파일로 기록할지 여부
    record_last_run => true
    # 마지막 시점을 기록할 파일 경로 (도커 내부 경로)
    last_run_metadata_path => "/usr/share/logstash/data/.logstash_jdbc_last_run_v3"
  }
}

filter {
  mutate {
    # 필드 이름을 스프링 부트 객체 구조([객체명][필드명])와 정확히 맞춤
    rename => {
      "book_id" => "[book][id]"
      "book_title" => "[book][title]"
      "user_id" => "[user][id]"
      "user_nickname" => "[user][nickname]"
      "created_at" => "createdAt" # Java의 카멜케이스와 맞춤
    }
    # 불필요한 메타데이터 삭제 (선택사항)
    remove_field => ["@version", "@timestamp"]
  }
}

output {
  elasticsearch {
    # localhost 대신 서비스 이름(elasticsearch) 사용
    hosts => ["${ES_HOSTS}"]
    index => "reviews"
    document_id => "%{id}"
  }
}